###################################################################################################
#                                                                                                 #
#                               Basics of working with networks in R                              #
#                                                                                                 #
###################################################################################################

###################################################################################################
# Preliminaries                                                                                   #
###################################################################################################

# Loading the necessary libraries:
library(sna)

# sna stands for social network analysis. This library contains several routines for analysing networks.
# See the user guide for more information: https://cran.r-project.org/web/packages/sna/sna.pdf

###################################################################################################
# Part 1: Creating a network from an adjacency matrix                                             #
###################################################################################################

# A random graph is a graph where the vertices are fixed, but the edges are drawn randomly and 
# independently from a Bernoulli distribution.

# Create an adjacency matrix for a single (m = 1) random graph with n vertices and edge probability tprob:
A <- rgraph(n=10, m=1, tprob=.25)

# Convert the adjacency matrix into a network object:
net_1 <- network(A, directed=TRUE, loops=FALSE, bipartite=FALSE, matrix.type="adjacency")

# We can also just use the defaults and write:
net_1 <- network(A)

# Summarise information about our network:
summary(net_1)

# A simple plot of the network:
plot(net_1)

###################################################################################################
# Part 2: Creating a network from an edge list                                                    #
###################################################################################################

# Setting the random seed for reproducibility:
set.seed(1)

# "Random" numbers generated by a computer are not really random, but they can seem to be to humans.
# By setting the random "seed", we fix the sequence of random numbers. The next random graph we 
# create will be the same upon repeated runs of this script.

# We can also use rgraph to create an edge list:
el <- rgraph(n=10, m=1, tprob=.25, return.as.edgelist=T)

# The edge list is an [m x 3] matrix where m is the number of edges. The first column is the vertex
# the edge originates at, the second the vertex it terminates at and the final one the weight:
el

# We can create, plot and summarise this network as before:
net_2 <- network(el, directed=TRUE, loops=FALSE, bipartite=FALSE, matrix.type="edgelist")
summary(net_2)
plot(net_2)

# We can also use the shorter version, as the network command automatically infers that this is an edge list:
net_2 <- network(el)

###################################################################################################
# Part 3: Examining properties of network objects                                                 #
###################################################################################################

# We can report various properties of our network:
is.network(net_2)        # Is it a network?
is.bipartite(net_2)      # Is it bipartite?
is.directed(net_2)       # Is it directed?
has.loops(net_2)         # Are loops allowed?  
network.size(net_2)      # What is the number of vertices, order of the network (as mentioned in the slides this is also sometimes called size)?
network.edgecount(net_2) # What is the number of edges?

# We can also access and modify particular edges:
summary(net_2)
net_2[3,5]               # The edge from vertex 3 to vertex 5 (not present).
net_2[1:3,1:3]           # A submatrix of the adjacency.
net_2[3,5] <- 1          # Adding and edge from vertex 3 to 5.
net_2[1,]  <- 1          # Set edges from vertex 1 to all other vertices.
summary(net_2)

# Notice that [1,1] remained 0 after the final modification, because we set loops to false.
# Similarly, networks with directed set to false will be symmetrised.

# We can also add vertices and edges with these commands:
add.vertices(net_2, 2)
add.edges(net_2, 11,12)

# And we can delete them:
get.edgeIDs(net_2, 11)
delete.edges(net_2, get.edgeIDs(net_2, 11))
delete.vertices(net_2, 11)
delete.vertices(net_2, 11)

###################################################################################################
# Part 4: Attributes of networks, vertices and edges                                              #
###################################################################################################

# List the attributes of our network:
list.network.attributes(net_2)

# We can then get the values a particular attribute:
get.network.attribute(net_2, "bipartite")
get.network.attribute(net_2, list.network.attributes(net_2)[2])

# Similary, vertex and edge attributes:
list.vertex.attributes(net_2)
list.edge.attributes(net_2)

# The built-in "na" attribute tells you if a vertex/edge is "missing" or not.
# This refers to missing data, not if an edge is present or absent:
get.vertex.attribute(net_2, "na")
get.edge.attribute(net_2, "na")

# The vertex names (ids):
get.vertex.attribute(net_2, "vertex.names")

# We can also add attributes:
set.edge.attribute(net_2, "new-attribute", 77)
list.edge.attributes(net_2)

# We can use either of the two to get the attribute values:
get.edge.attribute(net_2, "new-attribute")
get.edge.value(net_2, "new-attribute")

# Add a "gender" attribute for each vertex:
gender <- c(2,1,2,2,1,2,1,1,2,2)
set.vertex.attribute(net_2, "gender", gender)
list.vertex.attributes(net_2)
get.vertex.attribute(net_2, "gender")

# Change the vertex names:
names <- c("John", "Mary", "Tom", "Bob", "Ann", "Pete", "Kate", "Jill", "George", "Tim")
set.vertex.attribute(net_2, "vertex.names", names)
get.vertex.attribute(net_2, "vertex.names")
summary(net_2)

# Add a "year" attribute to the network:
set.network.attribute(net_2, "year", 2008)
list.network.attributes(net_2)
get.network.attribute(net_2, "year")

# Change the network to undirected by changing the "directed" attribute:
set.network.attribute(net_2, "directed", F)
summary(net_2)
plot(net_2)

# You can also delete attributes:
delete.network.attribute(net_2,"year")
delete.edge.attribute(net_2,"new-attribute")
delete.vertex.attribute(net_2,"gender")

# We can also get and set attributes using shorthand operators:
net_2 %n% "year" <- 2009          # %n% is for network
net_2 %n% "year"

net_2 %e% "new-attribute" <- 88   # %e% for edges.
net_2 %e% "new-attribute"     

net_2 %v% "gender" <- gender      # %v% for vertices.
net_2 %v% "gender"

summary(net_2)